services:
  logger.channel.sitestudio_config_management:
    parent: logger.channel_base
    arguments: [ 'sitestudio_config_management' ]
  site_studio.config_management:
    class: Drupal\sitestudio_config_management\SiteStudioConfigManagement
    arguments: [ '@extension.list.module', '@state' , '@config.factory' , "@logger.channel.sitestudio_config_management" ]
  sitestudio_config_management.config_subscriber:
    class: \Drupal\sitestudio_config_management\Config\ConfigImportEventSubscriber
    arguments: [ "@site_studio.config_management" , "@logger.channel.sitestudio_config_management" ]
    tags:
      - { name: event_subscriber }
