name: "Acquia CMS CRON"
on:
  schedule:
    - cron: "0 0 * * *"

  push:
    branches: [ ACMS-1451 ]
# Set ORCA related environment variables.
env:
  # Set Required API Keys.
  CONNECTOR_ID: ${{ secrets.CONNECTOR_ID }}
  GMAPS_KEY: ${{ secrets.GMAPS_KEY }}
  SEARCH_UUID: ${{ secrets.SEARCH_UUID }}
  SITESTUDIO_API_KEY: ${{ secrets.SITESTUDIO_API_KEY }}
  SITESTUDIO_ORG_KEY: ${{ secrets.SITESTUDIO_ORG_KEY }}
jobs:
  static_code_analysis:
    name: "static-code-analysis"
    strategy:
      fail-fast: false
      matrix:
        orca-job:
          - STATIC_CODE_ANALYSIS
          - STRICT_DEPRECATED_CODE_SCAN
    uses: ./.github/workflows/ci.workflow.yml
    with:
      orca-job: ${{ matrix.orca-job }}
      job-type: "static-code-analysis"
      use-mysql: false
  integrated-tests:
    name: "integrated-tests"
    strategy:
      fail-fast: false
      matrix:
        orca-job:
          - INTEGRATED_TEST_ON_PREVIOUS_MINOR
        acms-job:
          - integrated_php_unit_tests
          - integrated_existing_site_tests
          - backstop_tests
    uses: ./.github/workflows/ci.workflow.yml
    secrets: inherit # pass all secrets
    with:
      orca-job: ${{ matrix.orca-job }}
      acms-job: ${{ matrix.acms-job }}
      job-type: "integrated-tests"
      use-mysql: true
  isolated-tests:
    name: "isolated-tests"
    strategy:
      fail-fast: false
      matrix:
        orca-job:
          - ISOLATED_TEST_ON_CURRENT_DEV
          - ISOLATED_TEST_ON_NEXT_MINOR_DEV
          - INTEGRATED_TEST_ON_PREVIOUS_MINOR
    uses: ./.github/workflows/ci.workflow.yml
    secrets: inherit # pass all secrets
    with:
      orca-job: ${{ matrix.orca-job }}
      job-type: "isolated-tests"
      use-mysql: false
