name: Drush Security Check
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Drupal core dependencies and modules
        run: |
          composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

      - name: Run security check
        run: |
          ./vendor/bin/drush pm:security